version: "3"
services:
  corebuild:
    image: corebuild
    build:
      context: ./
      dockerfile: Dockerfile.composebase
  redis:
    image: redis:alpine
    ports:
      - "6379"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  postgres:
    image: postgres
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: secret
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  ingest:
    build:
      context: ./
      dockerfile: Dockerfile.ingest
    image: "openrelay/ingest:${TAG:-latest}"
    ports:
      - "8081:8080"
    command: ["/ingest", "postgres://ingest${POSTGRES_HOST:-postgres}", "env://POSTGRES_PASSWORD", "${REDIS_HOST:-redis:6379}", "${RELAY_ADDRESS}", "queue://ingest"]
    depends_on:
      - redis
      - corebuild
    environment:
      POSTGRES_PASSWORD: password
    restart: on-failure
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  bloomdata:
